# /coder/apps/config.yaml

apps:
  # Name of application in launcher. Name may consist of alphanumeric
  # characters, dashes, underscores. Names must begin with an alphanumeric
  # character. Names must be unique per application. Required.
  - name: my-rstudio
    scheme: http
    # Application port. Required.
    port: 8787
    # Host of the application to use when dialing. Defaults to localhost.
    # Optional.
    host: "localhost"
    headers:
      X-Forwarded-Proto: https
    # Working directory for the start command. Required.
    working-directory: /home/coder
    # File path to icon used in application launcher. Icons should be either
    # PNG, SVG, or JPG. Required.
    icon-path: /usr/lib/rstudio-server/www/images/rstudio-logo.png
    # Command to start the application. Required.
    command: /usr/lib/rstudio-server/bin/rserver
    # Array of arguments for command. Optional.
    args:
      - "--server-daemonize=1"
      - "--www-root-path=/api/v0/workspaces/${CODER_WORKSPACE_ID}/proxy/apps/my-rstudio/"
    # Health checks to get running application status. Can use exec or http
    # health checks to localhost. It is recommended to specify a health-check
    # although not strictly required. If one is not supplied then an http
    # request is sent to the application root path "/".
    health-check:
      # Exec commands require an exit code of '0' to report healthy.
      exec:
        command: "pgrep"
        args: ["rserver"]
      # http sends a GET request to the address specified via the parameters.
      # It expects a 200 status code to report healthy.
      http:
        # Scheme must be "http" or "https". If not specified it inherits
        # the application scheme. Optional.
        scheme: "http"
        # The host to use when dialing the address. If not specified it
        # inherits the application host. Optional.
        host: "localhost"
        # Port to use when dialing the application. If not specified it
        # inherits the application port. Optional.
        port: 8787
        status-code: 302
